swagger: '2.0'

info:
  version: "0.0.0"
  title: Dashboard API
schemes:
  - https
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
    description: |
      API Key should be passed as an authorization Header.
      The value for the Authorization header is expected to have the prefix "Token" or "Bearer".
paths:
  /datasets/{datasetId}/datapoint/:
    post:
      summary: |
        Creates a new `Datapoint` in the identified dataset
      description: |

        Sample curl requests
        ```
        curl --header "Authorization: Token token=09e9e1cff7e4434d8fd3bb6eb442a5fd86aa1c8f30a546c3aa719929323fdcf8" --data 'datapoint={ "ts": "2016-01-01T01:01:01.111Z", "value": "42"}' http://dashboard.gov.au/api/v1/datasets/1/datapoints
        ```

        ```
        curl --header "Authorization: Bearer 09e9e1cff7e4434d8fd3bb6eb442a5fd86aa1c8f30a546c3aa719929323fdcf8" --data 'datapoint={ "ts": "2016-01-01T01:01:01.111Z", "value": "42"}' http://dashboard.gov.au/api/v1/datasets/1/datapoints
        ```
      security:
       - api_key: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: datapoint
          description: |
            Datapoint object to be created
            Only ts and value are required for creation
          required: true
          schema:
            $ref: "#/definitions/Datapoint"
        - in: path
          name: datasetId
          description: ID of Dataset
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: Dataset not found
        "200":
          description: Datapoint found
          schema:
            $ref: "#/definitions/Datapoint"
        "400":
          description: Invalid data
  /datasets/{datasetId}/datapoint/{id}:
    get:
      summary: |
        Finds a datapoint by ID
      description: |

        Sample curl requests
        ```
        curl --header "Authorization: Token token=09e9e1cff7e4434d8fd3bb6eb442a5fd86aa1c8f30a546c3aa719929323fdcf8" http://dashboard.gov.au/api/v1/datasets/1/datapoints/1
        ```

        ```
        curl --header "Authorization: Bearer 09e9e1cff7e4434d8fd3bb6eb442a5fd86aa1c8f30a546c3aa719929323fdcf8" http://dashboard.gov.au/api/v1/datasets/1/datapoints/1
        ```
      security:
       - api_key: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID of Datapoint
          required: true
          type: integer
          format: int64
        - in: path
          name: datasetId
          description: ID of Dataset
          required: true
          type: integer
          format: int64
      responses:
        "404":
          description: Dataset not found
        "200":
          description: Datapoint created
          schema:
            $ref: "#/definitions/Datapoint"

definitions:
  Datapoint:
    type: object
    required:
      - ts
      - value
    properties:
      id:
        type: number
        format: double
      ts:
        type: string
        format: date-time
      value:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  Error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
