# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf664532fba6fc4356e32f0368b24ff04ebaba9783f2cbfaab6e494dd15aeca01be91a5cd48032e7f91311b1c2c46516db68c1af8008cba47d1466504db6e1cb

test:
  secret_key_base: eb9f726a789f9dab9026b35fc993db42a870ea6b02449c27db5b66cbe9e573a28d7c3e63fdf4e9d64551ec1824e00930da7913e1d2b3c8c4dfcc468054aaaf85

cloudfoundry:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
